api/urls.py
__author__ = 'jschnall'

from django.conf.urls import patterns, include, url
from rest_framework import routers
from api.views import *

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.include_root_view = True
router.register(r'users', UserViewSet)
router.register(r'compositions', CompositionViewSet)
router.register(r'parts', PartViewSet)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^/rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),
    #url(r'^/rest-auth/google/$', GoogleSignIn.as_view(), name='google_signin'),
)

exquisitecorpse/urls.py
__author__ = 'jschnall'

from django.conf.urls import patterns, include, url
from exquisitecorpse import views

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

#router = routers.SimpleRouter()
#router.register(r'parts', views.PartViewSet)
#urlpatterns = router.urls

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^compositions/$', views.CompletedCompositionList.as_view(), name='completed_composition_list'),
    url(r'^compositions/available/$', views.AvailableCompositionList.as_view(), name='available_composition_list'),
    url(r'^compositions/add/$', views.CompositionCreate.as_view(), name='composition_create'),
    url(r'^compositions/(?P<pk>\d+)/$', views.CompositionDetails.as_view(), name='composition_details'),
    url(r'^compositions/(?P<pk>\d+)/update/$', views.CompositionUpdate.as_view(), name='composition_update'),
    url(r'^compositions/(?P<pk>\d+)/delete/$', views.CompositionDelete.as_view(), name='composition_delete'),
    url(r'^compositions/(?P<pk>\d+)/add_part/$', views.PartCreate.as_view(), name='part_create'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^dashboard/(?P<category>\w+)/$', views.Dashboard.as_view(), name='dashboard'),
    #url(r'^parts/add/$', views.PartCreate.as_view(), name='part_create'),
    url(r'^parts/(?P<pk>\d+)/$', views.PartDetails.as_view(), name='part_details'),

    #url(r'^', include(router.urls)),

    # Ajax requests
    url(r'^like_part/$', views.PartLike.as_view(), name='part_like'),
    url(r'^like_composition/$', views.CompositionLike.as_view(), name='composition_like'),
    url(r'^favorite_composition/$', views.CompositionFavorite.as_view(), name='composition_favorite'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('exquisitecorpse.urls', namespace='corpse')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
)

exquisitecorpse/forms.py
__author__ = 'jschnall'

from django.core.urlresolvers import reverse
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Submit, Layout, Field, Fieldset
from crispy_forms.bootstrap import FormActions

from api.models import Composition, Part


class CompositionForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(CompositionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-compositionForm'
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(
            Fieldset(
                'New Composition',
                'title',
                'theme',
                #'join_policy',
                'rounds',
                'max_users',
                'min_part_chars',
                'max_part_chars',
            ),
            FormActions (
                Submit('create', 'Create'),
                Button('cancel', 'Cancel',
                       css_class='btn-default',
                       onclick='window.location.href="{}"'.format(reverse('corpse:dashboard')))
            )
        )

    class Meta:
        model = Composition
        fields = ['max_users', 'title', 'theme', 'rounds', 'min_part_chars', 'max_part_chars', ] #'join_policy'


class PartForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PartForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-partForm'
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit('create', 'Create'))
        self.helper.add_input(Button('cancel', 'Cancel',
                                     css_class='btn-default',
                                     onclick='window.location.href="{}"'.format(reverse('corpse:dashboard'))))
        self.helper.layout = Layout(
            Field('text', id="text-field", title="Text"),
            Field('segue', id="segue-field", title="Segue"),
        )

    class Meta:
        model = Part
        fields = ['text', 'segue']

exquisitecorpse/views.py
__author__ = 'jschnall'

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import View, CreateView, DeleteView, UpdateView

from rest_framework import viewsets
from rest_framework import mixins
from rest_framework import renderers
from rest_framework.response import Response

import serializers


import json

from api.models import *
from forms import *
from mixins import *

class IndexView(TemplateView):
    template_name = 'exquisitecorpse/index.html'

    def get_context_data(self, **kwargs):
        latest_compositions = Composition.objects.filter(completed__isnull=False).order_by('-completed')[:5]
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest_compositions'] = latest_compositions
        return context


class CompositionList(ListView):
    queryset = Composition.objects.order_by('-updated')
    template_name = 'exquisitecorpse/composition_list.html'
    context_object_name = 'compositions'
    paginate_by = settings.EXQUISITE_CORPSE['PAGINATE_BY']
    nav_size = settings.EXQUISITE_CORPSE['NAV_PAGINATE_BY']

    def get_context_data(self, **kwargs):
        paginator, page, object_list, is_paginated = self.paginate_queryset(self.queryset, self.paginate_by)
        nav_paginator = Paginator(range(1, paginator.num_pages + 1), self.nav_size)
        page_nums = nav_paginator.page(1 + (page.number-1) // self.nav_size)

        context = super(CompositionList, self).get_context_data(**kwargs)
        context['page_nums'] = page_nums
        return context


class AvailableCompositionList(CompositionList):
    def get_queryset(self):
        return Composition.objects.filter(Q(start_time__isnull=True) | Q(start_time__gt=timezone.now())).order_by('-updated')


class CompletedCompositionList(CompositionList):
    def get_queryset(self):
        return Composition.objects.filter(completed__isnull=False).order_by('-completed')


class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'exquisitecorpse/dashboard.html'
    context_object_name = 'compositions'

    QUEUED = 'queued'
    ACTIVE = 'active'
    COMPLETED = 'completed'
    FAVORITES = 'favorites'
    CATEGORY_CHOICES = (
        (QUEUED, 'Queued'),
        (ACTIVE, 'Active'),
        (COMPLETED, 'Completed'),
        (FAVORITES, 'Favorites'),
    )

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['queued_count'] = Composition.objects.filter(users=self.request.user).filter(Q(start_time__isnull=True) | Q(start_time__gt=timezone.now())).count()
        context['active_count'] = Composition.objects.filter(users=self.request.user, start_time__gt=timezone.now(), completed__isnull=True).count()
        context['completed_count'] = Composition.objects.filter(users=self.request.user, completed__isnull=False).count()
        context['favorite_count'] = Composition.objects.filter(favorites=self.request.user).count()
        return context

    def get_queryset(self):
        category = self.kwargs.get('category', None)

        if category == self.QUEUED:
            return Composition.objects.filter(users=self.request.user).filter(Q(start_time__isnull=True) | Q(start_time__gt=timezone.now())).order_by('-updated')
        elif category == self.ACTIVE:
            return Composition.objects.filter(users=self.request.user, start_time__gt=timezone.now(), completed__isnull=True).order_by('-updated')
        elif category == self.COMPLETED:
            return Composition.objects.filter(users=self.request.user, completed__isnull=False).order_by('-completed')
        elif category == self.FAVORITES:
            return Composition.objects.filter(favorites=self.request.user).order_by('-updated')


class CompositionDetails(DetailView):
    model = Composition
    template_name = 'exquisitecorpse/composition_details.html'


class CompositionCreate(LoginRequiredMixin, CreateView):
    model = Composition
    template_name = 'exquisitecorpse/composition_create.html'
    form_class = CompositionForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.active_user = self.request.user
        response = super(CompositionCreate, self).form_valid(form)
        form.instance.users.add(self.request.user)
        return response

    def get_success_url(self):
        return reverse_lazy('corpse:composition_details', args=(self.object.pk,))


class CompositionUpdate(LoginRequiredMixin, IsOwnerMixin, UpdateView):
    model = Composition
    template_name = 'exquisitecorpse/composition_create.html'
    form_class = CompositionForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        response = super(CompositionCreate, self).form_valid(form)
        form.instance.users.add(self.request.user)
        return response

    def get_success_url(self):
        return reverse_lazy('corpse:composition_details', args=(self.object.pk,))


class ToggleUserM2MFieldView(LoginRequiredMixin, AjaxableResponseMixin, View):
    '''
    Toggles the current user in an M2M field
    '''

    def post(self, request):
        try:
            pk = request.POST['pk']
            obj = self.model.objects.get(pk=pk)
            m2m_field = getattr(obj, self.field)
            exists = request.user in m2m_field.all()
            if exists:
                m2m_field.remove(request.user)
            else:
                m2m_field.add(request.user)
            return JsonResponse({'count': m2m_field.count(), 'exists': not exists})
        except:
            raise ImproperlyConfigured('Valid "model" and M2M "field" are required.')


class CompositionDelete(LoginRequiredMixin, IsOwnerMixin, DeleteView):
    model = Composition
    success_url = reverse_lazy('composition_list')
    #template_name = 'exquisitecorpse/composition_delete.html'


class PartDetails(DetailView):
    model = Composition
    template_name = 'exquisitecorpse/part_details.html'


class PartCreate(LoginRequiredMixin, CreateView):
    model = Part
    template_name = 'exquisitecorpse/part_create.html'
    form_class = PartForm

    def get_context_data(self, **kwargs):
        composition_id = self.kwargs.get('pk', None)
        composition = Composition.objects.get(pk=composition_id)
        context = super(PartCreate, self).get_context_data(**kwargs)
        context['composition'] = composition
        return context

    def form_valid(self, form):
        composition_id = self.kwargs.get('pk', None)
        form.instance.composition = Composition.objects.get(pk=composition_id)
        form.instance.owner = self.request.user
        return super(PartCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('corpse:part_details', args=(self.object.pk,))


'''
class PartViewSet(mixins.ListModelMixin,
                  mixins.CreateModelMixin,
                  mixins.RetrieveModelMixin,
                  viewsets.GenericViewSet):
    queryset = Part.objects.all()
    renderer_classes = (renderers.TemplateHTMLRenderer,)
    template_name = 'exquisitecorpse/part_create.html'
    form_class = PartForm

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        if serializer.is_valid():
            serializer.save(owner=self.request.user)
            return HttpResponse(status=201)
        return HttpResponse(status=400)

    def retrieve(self, request, *args, **kwargs):
        self.object = self.get_object()
        return Response({'part': self.object}, template_name='exquisitecorpse/part_details.html')
'''

# Ajax
class PartLike(ToggleUserM2MFieldView):
    model = Part
    field = 'likes'


class CompositionLike(ToggleUserM2MFieldView):
    model = Composition
    field = 'likes'


class CompositionFavorite(ToggleUserM2MFieldView):
    model = Composition
    field = 'favorites'

templates/exquisitecorpse/_pager.html
<div class="text-center">
    <ul class="pagination pagination-centered">
        {% if page_obj.has_previous %}
            <li><a href="?page=1"><<</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
        {% else %}
            <li class="disabled"><a href="#"><<</a></li>
            <li class="disabled"><a href="#"><</a></li>
        {% endif %}

        {% for item in page_nums %}
            <li {% if page_obj.number == item %} class="active" {% endif %}><a href="?page={{ item }}">{{ item }}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
        {% else %}
            <li class="disabled"><a href="#">></a></li>
            <li class="disabled"><a href="#">>></a></li>
        {% endif %}
    </ul>
 </div>

templates/exquisitecorpse/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
      <title>Exquisite Corpse - {% block title %}{% endblock %}</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      -->
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'exquisitecorpse/css/styles.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="{% static 'exquisitecorpse/js/my_jquery.js' %}"></script>
      {% block extra_head %}
      {% endblock %}
    </head>

    <body>
      {% block body_block %}
      <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">ExquisiteCorpse</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              {% url 'corpse:dashboard' as dashboard_url %}
              {% url 'corpse:completed_composition_list' as completed_url %}
              {% url 'corpse:available_composition_list' as available_url %}
              {% url 'corpse:composition_create' as create_url %}

              <li {% if dashboard_url in request.get_full_path %}class="active"{% endif %}><a href="{% url 'corpse:dashboard' 'queued' %}">Home</a></li>
              <li {% if request.get_full_path == completed_url %}class="active"{% endif %}><a href="{{ completed_url }}">Browse</a></li>
              <li {% if request.get_full_path == available_url %}class="active"{% endif %}><a href="{{ available_url }}">Join</a></li>
              <li {% if request.get_full_path == create_url %}class="active"{% endif %}><a href="{{ create_url }}">Create</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
              <!--
                <li>
                  <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                  </form>
                </li>
              -->
              {% if request.user.is_authenticated %}
                <li><a href="/accounts/logout/"><span class="glyphicon glyphicon-log-out"></span> {{ request.user.username }}</a></li>
              {% else %}
                <!--
                <li><a href="/accounts/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                -->
                <li><a href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <div class="container">
          {% block container_block %}{% endblock %}
      </div>
    </body>
    {% endblock %}
</html>

templates/exquisitecorpse/composition_about.html
<script type="text/javascript">

    $(document).ready(function() {
        $("#createPart").click(function(e) {
            e.preventDefault();
            var url = $(this).attr("data-url");
            $.post(url, {}, function(response){
                document.location=url;
            });
        });
    });
</script>

<div class="row">
    <div class="col-xs-12">
        {% if request.user.is_authenticated %}
            {% if not composition.start_time %}
            <!-- Game hasn't started yet -->
                {% if request.user == composition.owner %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary">
                            <span class="fa fa-pencil" aria-hidden="true"></span> Start Game
                        </button>
                        <button type="button" class="btn btn-default">
                            <span class="fa fa-user-plus" aria-hidden="true"></span> Invite
                        </button>
                        <button type="button" class="btn btn-default">
                            <span class="fa fa-trash" aria-hidden="true"></span> Delete
                        </button>
                    </div>
                {% elif request.user in composition.users.all %}
                    <button type="button" class="btn btn-primary">Quit Game</button>
                {% else %}
                    <button type="button" class="btn btn-primary">Join Game</button>
                {% endif %}
            {% else %}
                <!-- Game has started -->
                {% if request.user == composition.active_user %}
                    <a role="button" class="btn btn-primary" href="{% url 'corpse:part_create' composition.pk %}">
                        <span class="fa fa-pencil" aria-hidden="true"></span> Your turn
                    </a>
                {% else %}
                    <button type="button" class="btn disabled">
                        <span class="fa fa-pencil" aria-hidden="true"></span> {{ composition.active_user.username }}'s turn
                    </button>

                {% endif %}
            {% endif %}
        {% endif %}
    </div>
</div>

<br>
<br>

<div class="row">
    <!-- TODO: single line ellipsized, click to expand -->
    <div class="col-xs-4 cols-md-2">Players ({{ composition.users.count }}): </div>
    <div class="col-xs-8 cols-md-10 text-muted">
        {{ composition.users.first }}
        {% for user in composition.users.all|slice:"1:" %}
            , {{ user }}
        {% endfor %}
    </div>
</div>

<div class="row">
    <div class="col-xs-4 cols-md-2">Rounds:</div>
    <div class="col-xs-8 cols-md-10 text-muted">{{ composition.rounds }}</div>
</div>

<div class="row">
    <div class="col-xs-4 cols-md-2">Rounds:</div>
    <div class="col-xs-8 cols-md-10 text-muted">{{ composition.rounds }}</div>
</div>

<div class="row">
    <div class="col-xs-4">Min part size:</div>
    <div class="col-xs-8 text-muted">{{ composition.min_part_chars }}</div>
</div>

<div class="row">
    <div class="col-xs-4 cols-md-2">Max part size:</div>
    <div class="col-xs-8 cols-md-10 text-muted">{{ composition.max_part_chars }}</div>
</div>

templates/exquisitecorpse/composition_create.html
{% extends "exquisitecorpse/base.html" %}
{% load crispy_forms_tags %}

    {% block extra_head %}
        {% load staticfiles %}
    {% endblock %}

    {% block container_block %}
        {% crispy form %}
    {% endblock %}

templates/exquisitecorpse/composition_details.html
{% extends "exquisitecorpse/base.html" %}
  {% block extra_head %}
    {% load staticfiles %}
  {% endblock %}

  {% block container_block %}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#text" aria-controls="text" role="tab" data-toggle="tab">Text</a></li>
      <li role="presentation"><a href="#parts" aria-controls="parts" role="tab" data-toggle="tab">Parts</a></li>
      <li role="presentation"><a href="#about" aria-controls="about" role="tab" data-toggle="tab">About</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="text">{% include 'exquisitecorpse/composition_text.html' %}</div>
      <div role="tabpanel" class="tab-pane fade" id="parts">{% include 'exquisitecorpse/part_list.html' %}</div>
      <div role="tabpanel" class="tab-pane fade" id="about">{% include 'exquisitecorpse/composition_about.html' %}</div>
    </div>
  {% endblock %}

templates/exquisitecorpse/composition_list.html
{% extends 'exquisitecorpse/base.html' %}
  {% block extra_head %}
    {% load staticfiles %}
  {% endblock %}

  {% block container_block %}
      {% for composition in compositions %}
        {% include 'exquisitecorpse/composition_list_item.html' %}
      {% endfor %}
      {% include 'exquisitecorpse/pager.html' %}
  {% endblock %}

templates/exquisitecorpse/composition_list_item.html
  <a href="{% url 'corpse:composition_details' composition.id %}" class="list-group-item">
    <span class="badge"><span class="fa fa-star" aria-hidden="true"></span> {{ composition.favorites.count }} </span>
    <span class="badge"><span class="fa fa-thumbs-up" aria-hidden="true"></span> {{ composition.likes.count }} </span>
    <h4 class="list-group-item-heading inline-block text-overflow">{{ composition.title }}</h4>
    <h5 class="list-group-item-text">{{ composition.owner.username }}</h5>
  </a>

templates/exquisitecorpse/dashboard.html
{% extends 'exquisitecorpse/base.html' %}
{% block container_block %}
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Josh</strong> likes <a href="{% url 'corpse:composition_details' 21 %}" class="alert-link">Composition Name</a>
    </div>

    {% url 'corpse:dashboard' 'queued' as queued_url %}
    {% url 'corpse:dashboard' 'active' as active_url %}
    {% url 'corpse:dashboard' 'completed' as completed_url %}
    {% url 'corpse:dashboard' 'favorites' as favorites_url %}
    <ul class="nav nav-pills">
      <li role="presentation" {% if request.get_full_path == queued_url %}class="active"{% endif %}>
          <a href="{{ queued_url }}">Queued <span class="badge">{{ queued_count }}</span></a>
      </li>
      <li role="presentation" {% if request.get_full_path == active_url %}class="active"{% endif %}>
          <a href="{{ active_url }}">Active <span class="badge">{{ active_count }}</span></a>
      </li>
      <li role="presentation" {% if request.get_full_path == completed_url %}class="active"{% endif %}>
          <a href="{{ completed_url }}">Completed <span class="badge">{{ completed_count }}</span></a>
      </li>
      <li role="presentation" {% if request.get_full_path == favorites_url %}class="active"{% endif %}>
          <a href="{{ favorites_url }}">Favorites <span class="badge">{{ favorite_count }}</span></a>
      </li>
    </ul>

    <br>
    <div class="list-group">
    {% for composition in compositions %}
        {% if request.get_full_path == queued_url %}
        {% elif request.get_full_path == active_url %}
        {% elif request.get_full_path == completed_url or request.get_full_path == favorites_url %}
            {% include 'exquisitecorpse/composition_list_item.html' %}
        {% endif %}
    {% empty %}
    <!-- no entries, show placeholder-->
    <center><h1><small>(No items available)</small></h1></center>
    {% endfor %}
    </div>
{% endblock %}

templates/exquisitecorpse/index.html
{% extends "exquisitecorpse/base.html" %}
  {% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'exquisitecorpse/css/index.css' %}">
  {% endblock %}

  {% block container_block %}
    <div class="jumbotron">
      <h1>Exquisite Corpse</h1>
      <p>"A method by which a collection of words or images is collectively assembled..."</p>
    </div>

    <div class="row">

      <div class="col-md-3">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="col-md-3">
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      </div>

      <div class="col-md-3">
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
      </div>

      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><a href="#">Recent Compositions</a></li>
          {% if latest_compositions %}
            {% for composition in latest_compositions %}
              <li><a href="/compositions/{{ composition.id }}">{{ composition.title }}</a></li>
            {% endfor %}
          {% else %}
            <p>No compositions available.</p>
          {% endif %}
        </ul>
      </div>

      <div class="clearfix visible-lg"></div>
    </div>
  {% endblock %}

templates/exquisitecorpse/part_create.html
{% extends "exquisitecorpse/base.html" %}
{% load crispy_forms_tags %}

    {% block extra_head %}
        {% load staticfiles %}
    {% endblock %}

    {% block container_block %}
        <h4><center>{{ composition.title }}</center></h4>

        <div class="row pull-right">
            <div class="col-xs-12 text-muted pull-right" >Round {{ composition.current_round }} of {{ composition.rounds }}</div>
        </div>

        </br>
        </br>

        <div class="row">
            <div class="col-xs-12"><h5>...{{ composition.newest_part.segue }}</h5></div>
        </div>
        </br>

        {% crispy form %}
  {% endblock %}

templates/exquisitecorpse/part_list.html
<script type="text/javascript">
    $(document).ready(function() {
        $(".likes").click(function(e) {
            e.preventDefault();
            var pk = $(this).attr("data-pk");
            var data = {
                "pk": pk
            }
            $.ajax({
                "type": "POST",
                "dataType": "json",
                "url": "{% url 'corpse:part_like' %}",
                "data": data,
                "success": function(result) {
                    //console.log(result["likes"]);
                    $("#like-count-" + pk).html(result["count"]);
                    if (result["exists"]) {
                        $("#like-icon-" + pk).removeClass("fa-thumbs-o-up").addClass("fa-thumbs-up");
                    } else {
                        $("#like-icon-" + pk).removeClass("fa-thumbs-up").addClass("fa-thumbs-o-up");
                    }

                },
            });
        });
    });
</script>
{% csrf_token %}
{% for part in composition.part_set.all|dictsort:'created' %}
    {% include 'exquisitecorpse/part_list_item.html' %}
{% endfor %}